### ISSUE TITLE
Keep newline characters

### ISSUE THREAD

**Issue by gjuric** [antham/ghokin#1]
Is it possible to add a flag that would make the formatter not strip newline characters from the end of the file?

**Comment by antham** [comment]
Hi,
so you would like to propose a flag to strip everything but add a new extra line at the end of the file ?

**Comment by antham** [comment]
It's a bug, I didn't pay attention to this, I'm going to fix it.

**Comment by antham** [comment]
@gjuric can you tell me if it's solved the problem for you ?

**Comment by gjuric** [comment]
Works! Thank you.
