### ISSUE TITLE
Support files which starts with BOM unicode character

### ISSUE THREAD

**Issue by lavjamanxd** [antham/ghokin#12]
**Issue**
We are trying to format our feature files, but looks like it is not possible if it's encoded with e.g UTF-8 or Unicode. 

**Update**
With further investigations, it turned out that the root of the problem is not the Encoding.
It seems the [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) character is the culprit in this case.

**How to reproduce**
With BOM 
[with-bom-character.zip](https://github.com/antham/ghokin/files/3068609/with-bom-character.zip)
1. ghokin.exe check with-bom-character.feature
2. Fails with Parser error

Without BOM
[without-bom-character.zip](https://github.com/antham/ghokin/files/3068610/without-bom-character.zip)
1. ghokin.exe check without-bom-character.feature
2. Works fine

**Comment by antham** [comment]
Thanks for reporting, it's fixed sorry for the delay
