### ISSUE TITLE
Double backslash removed in table

### ISSUE THREAD

**Issue by AffeAli** [antham/ghokin#120]
Two backslashes in a table get turned into one. This is annoying as I decode the string and cannot use backslashes this way.
Also this means that running ghokin multiple times gives different results.

Example:
```
Feature: f
  Scenario: s
    Given a
      | name      |
      | hello\\\n |
```
gets formatted into:
```
Feature: f
  Scenario: s
    Given a
      | name     |
      | hello\\n |
```
which in turn gets formatted into
```
Feature: f
  Scenario: s
    Given a
      | name    |
      | hello\n |
```

**Comment by antham** [comment]
Here the release with the fix => https://github.com/antham/ghokin/releases/tag/v3.4.3
