### ISSUE TITLE
Steps containing Data-Table and DocString fail

### ISSUE THREAD

**Issue by DDtKey** [antham/ghokin#124]
Hi there! 
First of all thanks for the linter and its maintenance!

I just wonder why this is disallowed? 🤔 

Example:

```gherkin
    When user does something
      """
        ok
      """
      | a | b |
```
lead to
```
Parser errors:
(x:y): expected: #EOF, #StepLine, #TagLine, #ExamplesLine, #ScenarioLine, #RuleLine, #Comment, #Empty, got '      | a | b |
```

But I don't see any mentions in [reference](https://cucumber.io/docs/gherkin/reference/) that it's disallowed to combine them
Moreover, it works with ~~quite a lot of~~ cucumber-runners, [JetBrains plugin](https://plugins.jetbrains.com/plugin/9164-gherkin) also marks such syntax as valid.

**Comment by antham** [comment]
Hi,
here we are using the cucumber go library to parse th file, the message above is from the library.

**Comment by DDtKey** [comment]
Oh, got it, in that case the issue should be redirected, since there seems to be a difference in the behavior of the implementations for different languages.

Thanks

**Comment by antham** [comment]
I checked if it could come from another part of the code but it seems to be really coming from their side.

**Comment by antham** [comment]
@DDtKey Hi, from what I get in the ticket to cucumber, nothing will be done to support that behaviour right?

**Comment by DDtKey** [comment]
Yes, I think so, the behavior will be documented.

Let's close the issue. Thank you!

**Comment by antham** [comment]
Thank you for reporting that here and to cucumber!
