### ISSUE TITLE
Memory of column widths fails when there are inline comments

### ISSUE THREAD

**Issue by xyu** [antham/ghokin#128]
When there are either blank lines or comments between rows of a table, for example a feature file that looks something like this:

```feature
Feature: Test Formatter
  Scenario: Comment between rows
    Given table my_table
      | col a | col b |
      | 1     | 2     |
      # A comment about the row below
      | 3     | 4     |
```

On the latest 3.5.0 (as well as earlier) version of ghokin the 3rd row of the table gets formatted as if the column width should be sized interdependently of the rest of the table.

```bash
$ ghokin fmt stdout test.feature
```

Produces:

```feature
Feature: Test Formatter
  Scenario: Comment between rows
    Given table my_table
      | col a | col b |
      | 1     | 2     |
      # A comment about the row below
      | 3 | 4 |
```

**Comment by antham** [comment]
Hi,
thanks for reporting, it's going to be a bit hard to fix I think.

**Comment by antham** [comment]
Check the https://github.com/antham/ghokin/releases/tag/v3.5.1

**Comment by xyu** [comment]
Thanks!
