### ISSUE TITLE
Accept folder when using stdout

### ISSUE THREAD

**Issue by gjuric** [antham/ghokin#3]
It would be nice if `fmt stdout` would accept a directory like `fmt replace` does.

It would be an added bonus if there are any changes to be made the tool could exit with a non-zero exit code. This could then be checked when running other tests and fail a build if the files are not correctly formatted.

Showing what would change in the file if `replace` was being run instead would also be nice.

Come to think of it, maybe `stdout` should stay the same and another option called `check` could be introduced.

Let me know if you want me to open separate issues for each thing I mentioned.

**Comment by antham** [comment]
What is the use case exactly for your first statement ?

For the rest, I was thinking the same, having a command to tell you everything is not well formatted and yes I was thinking to add it as separated command like you said.

**Comment by gjuric** [comment]
If there would be a `check` command the first part is not important.

**Comment by antham** [comment]
I created #4 so I close this issue
