### ISSUE TITLE
Escaped pipe being formatted to invalid value

### ISSUE THREAD

**Issue by adrianduke** [antham/ghokin#50]
I've got a situation where I need to use a `|` in a table value. Godog accepts a `\|` as an escape sequence for the pipe, but Ghokin replaces it with `|`, breaking godog and cucumber.js:

Input:
```gherkin
Feature: Test

	Scenario: Pipe in table value
		Given I have a table:
			| a | b \| c |
```

Output:
```gherkin
Feature: Test

  Scenario: Pipe in table value
    Given I have a table:
      | a | b | c |
```

Expected:
```gherkin
Feature: Test

  Scenario: Pipe in table value
    Given I have a table:
      | a | b \| c |
```

**Comment by antham** [comment]
Hi, thanks for reporting check out https://github.com/antham/ghokin/releases/tag/v1.6.1
