### ISSUE TITLE
Formatting empty scenarios removes them

### ISSUE THREAD

**Issue by DavertMik** [antham/ghokin#59]
Thanks for the great formatter!
We faced one issue with removing empty scenarios. Unfortunately, I don't know Go so I can't make PR for this

Feature file:

```gherkin
Feature: A suite 1

Scenario: asdsad asdsad asdsad
  Given the user disconnects the water

Scenario: as 123 dsad
Scenario: adsad 
Scenario: asds asdsa ad
```

Result: 

```gherkin
Feature: A suite 1

  Scenario: asdsad asdsad asdsad
    Given the user disconnects the water

  Scenario: as 123 dsad

```

**Comment by antham** [comment]
Hi thanks for reporting.

I see where the problem is, I'm going to fix that when I will have a bit of time.

Cheers.

**Comment by antham** [comment]
Here we go => https://github.com/antham/ghokin/releases/tag/v1.6.2 @DavertMik

**Comment by DavertMik** [comment]
Thank you very much! :heart:
