### ISSUE TITLE
Feature description is too much indented

### ISSUE THREAD

**Issue by ealprr** [antham/ghokin#63]
The feature description is indented following `indent.tableAndDocString` option which seems strange.

Example of feature file from [gherkin reference](https://cucumber.io/docs/gherkin/reference/):

```gherkin
Feature: Multiple site support
  Only blog owners can post to a blog, except administrators,
  who can post to all blogs.

  Background:
    Given a global administrator named "Greg"
```

ghokin fmt stdout:

```gherkin
Feature: Multiple site support
      Only blog owners can post to a blog, except administrators,
      who can post to all blogs.

  Background:
    Given a global administrator named "Greg"
```

I would expect feature description to be indented as much as `Background `and `Scenario`.

I also suggest to drop separate configuration for indentation and use only a relative indent option:

```yaml
indent:
  level: [0-9]+
  character: (space|tab)
```

Indeed, I am not sure someone will use an asymmetric indentation. However, it will be easier to handle formatting with new feature in gherkin syntax (like the new `Rule` keyword):

```gherkin
Feature: Highlander

  Rule: There can be only One

    Example: Only One -- More than one alive
      Given there are 3 ninjas
```

Also, thank you for this tool!

**Comment by antham** [comment]
Sorry for this late answer.

This is fixed in the new release =>   #https://github.com/antham/ghokin/releases/tag/v2.0.0

About the second point you mentioned, I will add every new `keywords` to ghokin instead of doing that, considering there is not lot of` evolution on the gherkin language.
