### ISSUE TITLE
The format replace all CRLF end line by LF end line. We should be able to configure it

### ISSUE THREAD

**Issue by kevingermain** [antham/ghokin#72]
Everything are in the title

**Comment by antham** [comment]
Hi, thanks for reporting.

Can you tell me if the last version fix the issue ?

**Comment by antham** [comment]
@kevingermain Any news about that ?

**Comment by kevingermain** [comment]
@antham Sorry for the late reply, I will check and let you know. Thank you very much.

**Comment by antham** [comment]
Great thank you for this feedback ! @kevingermain
